### ISSUE TITLE
Problems with pyl

### ISSUE THREAD

**Issue by MilitaoLucas** [pcxod/olex2#8]
I couldn't find out what exactly is pyl if not a python interpreter that is a little different from the normal one. Is pyl compiled from source by the Olex2 team? Or is it some other project? I symlinked it to python and it worked better. I also removed PYTHONHOME from the current directory. So basically I could install pyscf to the conda environment and use it instead of using the Python provided in Olex2.

**Comment by pcxod** [comment]
Yes, indeed, this is in a private repository. The purpose of this small program is to run a Python script in Olex2's environment and could be done by the Python executable itself.

**Comment by MilitaoLucas** [comment]
Is there any major reason why it is done this way? Does it have any performance benefits?

**Comment by pcxod** [comment]
We never distributed Python executable, This few line program uses the same dynamic library Olex2 is compiled against but as an external process.
